[package]
name = "close_enough"
version = "0.1.0"
authors = ["***Phirstname*** ***Lastname*** <***redacted.email@redacted.nope***>"]

[dependencies]
clap = { version = "2.20.5", optional = true }

[features]
cli = ["clap"]
default = ["cli"]

[[bin]]
name = "ce"
path = "src/ce.rs"