[package]
name = "close_enough"
version = "0.1.1"
authors = ["***Phirstname*** ***Lastname*** <***redacted.email@redacted.nope***>"]

[dependencies.clap]
version = "2.20.5"
optional = true
default-features = false
features = ["color", "wrap_help"]

[features]
cli = ["clap"]
default = ["cli"]

[[bin]]
name = "cle"
path = "src/cle.rs"
