[package]
name = "close_enough"
version = "0.2.0"
authors = ["Pirh <pirh.badger@gmail.com>"]

[dependencies.clap]
version = "2.26"
optional = true
default-features = false
features = ["color", "wrap_help"]

[features]
cli = ["clap"]
default = ["cli"]

[[bin]]
name = "cle"
path = "src/cle.rs"
required-features = ["cli"]
